-- src/main/resource/data.sql

INSERT INTO TASK(ID, TITLE, DESCRIPTION, SCORE, STATUS)
VALUES(1, 'FIGMA', 'CRIAR O PROTOTIPO', 10, 0);

INSERT INTO TASK(ID, TITLE, DESCRIPTION, SCORE, STATUS)
VALUES(2, 'JAVA', 'ESTUDAR JAVA', 50, 10);